name: 이메일 알림 구독 신청
description: inflearn과 hola에 새로운 프로젝트가 올라오면 알림을 받습니다.
title: '[구독 신청] 이메일 알림 구독 신청'
labels:
  - 구독신청
body:
  - type: input
    id: email
    attributes:
      label: 알림을 받을 이메일 주소를 입력해주세요.
      description: 새로운 프로젝트가 올라오면 해당 이메일 주소로 알림을 보내드립니다.
      placeholder: email@example.com
    validations:
      required: true
  - type: checkboxes
    id: topics
    attributes:
      label: 알림을 받을 항목를 선택해주세요.
      description: AI가 프로젝트 공고의 제목과 태그를 분석해 구인 포지션을 분류합니다. 만약 아무것도 선택하지 않으면 새로운 모든 프로젝트에 대한 알림을 받습니다.
      options:
        - label: 프론트
        - label: 백엔드
        - label: 기획
        - label: 디자인
        - label: 마케팅
        - label: PM
