name: subscribe
on:
  issues:
    types: [opened, edited, reopened]
permissions:
  issues: write
jobs:
  subscribe:
    if: contains(github.event.issue.labels.*.name, '구독신청')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Set execute permission for script
        run: chmod +x ./subscribe.sh

      - name: Subscribe
        id: subscribe
        continue-on-error: true
        run: |
          output=$(./subscribe.sh "${{ github.event.issue.body}}" "${{ secrets.API_GATEWAY_URL }}")
          echo "result=$output" >> $GITHUB_OUTPUT

      - name: Add success comment
        if: steps.subscribe.outcome == 'success'
        run: |
          gh issue comment "$NUMBER" --body "$BODY"
        env:
          NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BODY: >
            구독 신청이 완료되었습니다. 새로운 프로젝트가 올라오면 해당 이메일 주소로 알림을 보내드립니다.

            **구독 정보를 수정하고 싶다면?**
            > Issue를 수정해주세요. 자동화된 프로세스로 구독정보를 수정합니다.

            **구독을 취소하고 싶다면?**
            > Issue를 Close 해주세요. 자동화된 프로세스로 구독을 취소합니다.

      - name: Add failure comment
        if: steps.subscribe.outcome != 'success'
        run: |
          gh issue comment "$NUMBER" --body "$BODY"
        env:
          NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BODY: >
            구독 신청 중 오류가 발생했습니다. 다음 오류 메시지를 확인해주세요:

            ```
            ${{ steps.subscribe.outputs.result }}
            ```

            문제가 지속되면 관리자에게 문의해주세요.
