name: subscribe
on:
  issues:
    types: [opened, edited, reopened]
permissions:
  issues: write
jobs:
  subscribe:
    if: contains(github.event.issue.labels.*.name, '구독신청') && github.event.issue.state == 'open'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Set execute permission for script
        run: chmod +x ./scripts/subscribe.sh

      - name: subscribe
        continue-on-error: false
        run: |
          ./scripts/subscribe.sh "${{ github.event.issue.body}}" "${{ secrets.API_GATEWAY_URL }}"

      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BODY: |
            구독 신청이 완료되었습니다. 새로운 프로젝트가 올라오면 해당 이메일 주소로 알림을 보내드립니다.

            **모든 프로젝트에 대한 알림을 받고 싶다면?**
            > 선택된 항목이 없을 경우 모든 프로젝트에 대한 알림을 받습니다.

            **구독 정보를 수정하고 싶다면?**
            > Issue를 수정해주세요. 자동화된 프로세스로 구독정보를 수정합니다. 단, 이메일 주소를 수정하고 싶다면 먼저 Issue를 Close한 후 이메일 주소를 수정하고 다시 Issue를 Reopen 해주세요.

            **구독을 취소하고 싶다면?**
            > Issue를 Close 해주세요. 자동화된 프로세스로 구독을 취소합니다.
