name: subscribe
on:
  issues:
    types: [opened, edited, reopened]
jobs:
  subscribe:
    if: contains(github.event.issue.labels.*.name, '구독신청')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Set execute permission for script
        run: chmod +x ./subscribe.sh

      - name: subscribe
        run: |
          ./subscribe.sh "${{ github.event.issue.body}}"
