name: subscribe
on:
  issues:
    types: [opened, edited, reopened]
jobs:
  subscribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Subscribe
        run: |
          echo "start"
          echo "body: ${{ github.event.issue.body }}"
          echo "title: ${{ github.event.issue.title }}"
          echo "labels: ${{ github.event.issue.labels }}"
          echo "end"
